server:
  port: @product.port@
  servlet:
    context-path: /

spring:

 #security:
  #user:
  #  name: admin  # 认证用户名
  #  password: test1234  # 认证密码
 main:
   allow-bean-definition-overriding: true

mybatis-plus:
  mapperLocations: classpath:/sqlMapperXml/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


info:
  app.name: @project.name@
  company.name: daiyanping
  build.artifactId: @project.artifactId@
  build.modelVersion: @project.modelVersion@

# 配置ribbon 饥饿加载
#ribbon:
#  eager-load:
#    enabled: true
#    clients: springcloud-provider