
logging:
  config: classpath:logs/logback-dev.xml

spring:
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 3000ms
        min-idle: 0
    host: 192.168.109.128
    port: 6380
    password: test1234