server:
  port: @gateway.port@
  servlet:
    context-path: /

spring:
 main:
   allow-bean-definition-overriding: true
 cloud:
   gateway:
     #  跨域配置
     globalcors:
       corsConfigurations:
         '[/**]':
           allowedOrigins: "*"
           allowedHeaders: "*"
           allowCredentials: true
           allowedMethods:
             - GET
             - POST
             - OPTIONS
             - PUT
             - DELETE
     # 开启自动发现
     discovery:
       locator:
         enabled: true
     # 注意优先级问题，配置最前面的最先匹配
     routes:
       - id: product
         uri: lb://mymall-product
         predicates:
           - Path=/api/product/**
         filters:
           #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
           - StripPrefix=1 # 效果同上， 截取路径位数
       - id: coupon
         uri: lb://mymall-coupon
         predicates:
           - Path=/api/coupon/**
         filters:
           #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
           - StripPrefix=1 # 效果同上， 截取路径位数
       - id: member
         uri: lb://mymall-member
         predicates:
           - Path=/api/member/**
         filters:
           #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
           - StripPrefix=1 # 效果同上， 截取路径位数
       - id: order
         uri: lb://mymall-order
         predicates:
           - Path=/api/order/**
         filters:
           #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
           - StripPrefix=1 # 效果同上， 截取路径位数
       - id: ware
         uri: lb://mymall-ware
         predicates:
           - Path=/api/ware/**
         filters:
           #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
           - StripPrefix=1 # 效果同上， 截取路径位数
       - id: thrid-party
         uri: lb://mymall-third-party
         predicates:
           - Path=/api/thirdparty/**
         filters:
           #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
           - StripPrefix=1 # 效果同上， 截取路径位数
       - id: admin
         uri: lb://renren-fast
         predicates:
           - Path=/api/**  #前端项目直接先走renren-fast
         filters:
           - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment} #路径重写






info:
  app.name: @project.name@
  company.name: daiyanping
  build.artifactId: @project.artifactId@
  build.modelVersion: @project.modelVersion@
