server:
  port: @gateway.port@
  servlet:
    context-path: /

spring:
 main:
   allow-bean-definition-overriding: true








info:
  app.name: @project.name@
  company.name: daiyanping
  build.artifactId: @project.artifactId@
  build.modelVersion: @project.modelVersion@
