
spring:
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 3000ms
        min-idle: 0
    host: 127.0.0.1
    port: 6379
  #      password: test1234

  cloud:
    gateway:
      #  跨域配置
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
      # 开启自动发现
      discovery:
        locator:
          enabled: true
      # 注意优先级问题，配置最前面的最先匹配
      routes:
        - id: product
          uri: lb://mymall-product
          predicates:
            - Path=/api/product/**,/test/test
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
            - StripPrefix=1 # 效果同上， 截取路径位数
        - id: coupon
          uri: lb://mymall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
            - StripPrefix=1 # 效果同上， 截取路径位数
        - id: member
          uri: lb://mymall-member
          predicates:
            - Path=/api/member/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
            - StripPrefix=1 # 效果同上， 截取路径位数
        - id: order
          uri: lb://mymall-order
          predicates:
            - Path=/api/order/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
            - StripPrefix=1 # 效果同上， 截取路径位数
        - id: ware
          uri: lb://mymall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
            - StripPrefix=1 # 效果同上， 截取路径位数
        - id: thrid-party
          uri: lb://mymall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
            - StripPrefix=1 # 效果同上， 截取路径位数
        - id: thrid-party
          uri: lb://mymall-search
          predicates:
            - Path=/api/search/**
          filters:
            #- RewritePath=/api/(?<segment>.*),/$\{segment} #路径重写,去除/api 前缀路径
            - StripPrefix=1 # 效果同上， 截取路径位数
        - id: admin
          uri: lb://renren-fast
          predicates:
            - Path=/api/**  #前端项目直接先走renren-fast
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment} #路径重写
        - id: product-host-route #这个需要放在后面，否则我们的/api 接口就会出问题，api接口的还是由上面的路由规则处理
          uri: lb://mymall-product
          predicates:
            - Host= mymall.com #域名转发
        - id: search-host-route #这个需要放在后面，否则我们的/api 接口就会出问题，api接口的还是由上面的路由规则处理
          uri: lb://mymall-search
          predicates:
            - Host= search.mymall.com #域名转发
logging:
  config: classpath:logs/logback-dev.xml


