
spring:
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 3000ms
        min-idle: 0
    host: 127.0.0.1
    port: 6379
  #      password: test1234
logging:
  config: classpath:logs/logback-dev.xml


