server:
  port: @ware.port@
  servlet:
    context-path: /

spring:

 #security:
  #user:
  #  name: admin  # 认证用户名
  #  password: test1234  # 认证密码
 main:
   allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:/sqlMapperXml/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


info:
  app.name: @project.name@
  company.name: daiyanping
  build.artifactId: @project.artifactId@
  build.modelVersion: @project.modelVersion@

# 配置ribbon 饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients:
    - mymall-product
    - mymall-member
    - mymall-order
    - mymall-message

# feign配置
feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true