
spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  druid:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.109.129:3309/message?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    initial-size: 1
    max-active: 20
    min-idle: 1
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    #Oracle需要打开注释
    #validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      login-username: admin
      login-password: admin
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
 rabbitmq:
  listener:
    type: simple
    simple:
      retry:
        enabled: true
  host: 192.168.109.129
  port: 5672
  username: root
  password: test1234
  virtual-host: /
  connection-timeout: 0
 redis:
  lettuce:
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000ms
      min-idle: 0
  host: 192.168.109.129
  port: 6380
  password: test1234
 cache:
  type: redis
  redis:
    time-to-live: 12h

logging:
  config: classpath:logs/logback-dev.xml

hystrix:
  command:
    queryContents:
      execution:
        isolation:
          strategy: SEMAPHORE


