server:
  port: @order.port@
  servlet:
    context-path: /
  max-http-header-size:

spring:

 #security:
  #user:
  #  name: admin  # 认证用户名
  #  password: test1234  # 认证密码
 main:
   allow-bean-definition-overriding: true
 session:
   store-type: redis
mybatis-plus:
  mapperLocations: classpath:/sqlMapperXml/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


info:
  app.name: @project.name@
  company.name: daiyanping
  build.artifactId: @project.artifactId@
  build.modelVersion: @project.modelVersion@

# 配置ribbon 饥饿加载
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  eager-load:
    enabled: true
    clients:
    - mymall-member
    - mymall-product
    - mymall-cart
    - mymall-ware
    - mymall-message

feign:
  client:
    config:
      default: #默认所有客户端都用这个配置，否则readTimeout使用的LoadBalancerFeignClient.DEFAULT_OPTIONS，如果这里不进行配置，则会使用ribbon的readTimeout，connectTimeout
        readTimeout: 3600000
        connectTimeout: 10000
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

    # 审计信息暴露，sentinel 实时监控有用
management:
  endpoints:
    web:
      exposure:
        include: '*'
