
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #    url: jdbc:mysql://192.168.109.128:3309/oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      #    username: root
      #    password: 123456
      #    url: jdbc:mysql://192.168.109.129:8806/ENJOYDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      #    url: jdbc:mysql://127.0.0.1:8806/ENJOYDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      # nginx 代理mycat
      url: jdbc:mysql://192.168.109.129:13307/ENJOYDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: enjoy
      password: 123456
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  #sharding jdbc 分表配置
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.109.129:3309/oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        #    username: root
        #    password: 123456
        #    url: jdbc:mysql://192.168.109.129:8806/ENJOYDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        #    url: jdbc:mysql://127.0.0.1:8806/ENJOYDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        # nginx 代理mycat
        #         url: jdbc:mysql://192.168.109.129:13307/ENJOYDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        #Oracle需要打开注释
        #validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          login-username: admin
          login-password: admin
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.109.129:3310/oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        #    username: root
        #    password: 123456
        #    url: jdbc:mysql://192.168.109.129:8806/ENJOYDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        #    url: jdbc:mysql://127.0.0.1:8806/ENJOYDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        # nginx 代理mycat
        #         url: jdbc:mysql://192.168.109.129:13307/ENJOYDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        #Oracle需要打开注释
        #validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          login-username: admin
          login-password: admin
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true

    sharding:
      defaultDataSourceName: ds0
#      tables:
#        oms_order:
#          actual-data-nodes: ds$->{0..1}.oms_order
##          key-generator:
##            column: id
##            type: SNOWFLAKE
#          inline:
#            sharding-column: id
#            algorithm-expression: ds$->{id % 2 + 1}
#        oms_order_item:
#          actual-data-nodes: ds$->{0..1}.oms_order_item
##          key-generator:
##            column: id
##            type: SNOWFLAKE
#          inline:
#            sharding-column: id
#            algorithm-expression: ds$->{id % 2 + 1}



    props:
      sql:
        show: true


  rabbitmq:
    listener:
      type: simple
      simple:
        retry:
          enabled: true
        acknowledge-mode: manual #开启手动确认
    template:
      mandatory: true #开启失败通知
    host: 192.168.109.129
    port: 5672
    username: root
    password: test1234
    virtual-host: /
    connection-timeout: 0
    publisher-confirms: true
    publisher-returns: true
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 3000ms
        min-idle: 0
    host: 192.168.109.129
    port: 6380
    password: test1234
  cache:
    type: redis
    redis:
      time-to-live: 12h
sharding:
  jdbc:
    config:
      sharding:
        default-data-source-name: ds0

logging:
  config: classpath:logs/logback-dev.xml


