server:
  port: @search.port@
  servlet:
    context-path: /

spring:

 #security:
  #user:
  #  name: admin  # 认证用户名
  #  password: test1234  # 认证密码
 main:
   allow-bean-definition-overriding: true

 cloud:
  sentinel:
    transport:
      port: 8719
      dashboard: localhost:8080
 thymeleaf:
   cache: false
   suffix: .html


info:
  app.name: @project.name@
  company.name: daiyanping
  build.artifactId: @project.artifactId@
  build.modelVersion: @project.modelVersion@
