
spring:
  elasticsearch:
    rest:
      uris: http://192.168.109.129:9200
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 3000ms
        min-idle: 0
    host: 192.168.109.129
    port: 6380
    password: test1234

logging:
  config: classpath:logbak/logback-dev.xml


